importers:
  - importer: shelliesmqtt
    name: MQTT importer
    host: tcp://153.77.136.201:1883
    user: ""
    password: ""
    devices:
    prefix: /shellies
exporters:
  - exporter: mqttwebsocket
    name: MQTT websocket exporter
    host: ws://maqiatto.com:8883
    user: giacomo.spano@libero.it
    password: giacomo
controllers:
  - controller: mqttcontroller
    name: MQTT controller
    host: ws://maqiatto.com:8883
    user: "giacomo.spano@libero.it"
    password: "giacomo"
    prefix: giacomo.spano@libero.it
    topic: /controller/command

agents:
#  - name: lane2
#    type: lane
#    host: giacomocasa.duckdns.org:1883
#    user: giacomo
#    password: giacomo
#    topic: laneagents/command
#    publishtopic: laneagents/statusupdate

