# client ncr
importers:
  - importer: shelliesmqtt
    name: MQTT importer
#    host: tcp://153.77.136.201:1883
    host: tcp://192.168.1.143:1883
    user: "giacomo"
    password: "giacomo"
    prefix: shellies/
exporters:
  - exporter: mqttwebsocket
    name: MQTT websocket exporter
    host: ws://giacomocasa.duckdns.org:9001
    user: "giacomo"
    password: "giacomo"
    prefix: update
receivers:
  - receiver: mqttreceiver
    name: MQTT receiver
    host: ws://giacomocasa.duckdns.org:9001
    user: "giacomo"
    password: "giacomo"
    prefix: receiver/
  - receiver: mqttproxyreceiver
    name: MQTT receiver
    host: ws://giacomocasa.duckdns.org:9001
    user: "giacomo"
    password: "giacomo"
    prefix: proxyreceiver/
    topic: command
emulators:
  - emulator: shellyemulator
    name: "ShellyEmulator1x"
    id : "00001"
    host: tcp://192.168.1.143:1883
#    host: tcp://192.168.1.143:1883
    user: "giacomo"
    password: "giacomo"
    prefix: shellies/
    model: "SHPLG-S"
agents:
#  - name: lane2
#    type: lane
#    host: giacomocasa.duckdns.org:1883
#    user: giacomo
#    password: giacomo
#    topic: laneagents/CommandReceiver.command
#    publishtopic: laneagents/statusupdate

