importers:
  - importer: shelliesmqtt
    name: MQTT importer
    host: tcp://153.77.136.201:1883
    user: ""
    password: ""
    prefix: shellies/
exporters:
  - exporter: mqttwebsocket
    name: MQTT websocket exporter
    host: ws://giacomocasa.duckdns.org:9001
    user: "giacomo"
    password: "giacomo"
    prefix: update
controllers:
  - controller: mqttcontroller
    name: MQTT controller
    host: ws://giacomocasa.duckdns.org:9001
    user: "giacomo"
    password: "giacomo"
    prefix: ""
    topic: /controller/command
agents:
#  - name: lane2
#    type: lane
#    host: giacomocasa.duckdns.org:1883
#    user: giacomo
#    password: giacomo
#    topic: laneagents/command
#    publishtopic: laneagents/statusupdate

